# Generated by Django 2.2.13 on 2022-04-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220309_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128, verbose_name='股票代码')),
                ('name', models.CharField(max_length=128, verbose_name='股票简称')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.FloatField(null=True, verbose_name='开盘价')),
                ('high', models.FloatField(null=True, verbose_name='最高价')),
                ('close', models.FloatField(null=True, verbose_name='收盘价')),
                ('low', models.FloatField(null=True, verbose_name='最低价')),
                ('volume', models.FloatField(null=True, verbose_name='成交量')),
                ('price_change', models.FloatField(null=True, verbose_name='价格变动')),
                ('p_change', models.FloatField(null=True, verbose_name='涨跌幅')),
                ('ma', models.FloatField(null=True, verbose_name='均价')),
                ('turnover', models.FloatField(null=True, verbose_name='换手率')),
                ('lastclose', models.FloatField(null=True, verbose_name='前收盘价')),
                ('cjje', models.FloatField(null=True, verbose_name='成交金额')),
            ],
            options={
                'verbose_name_plural': '股票',
            },
        ),
    ]
