# Generated by Django 2.2.13 on 2022-04-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuPiao',
        ),
    ]
