# Generated by Django 2.2.4 on 2023-02-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_gupiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
            },
        ),
    ]
