# Generated by Django 2.2.4 on 2023-02-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
