# Generated by Django 2.2.13 on 2023-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '新闻'},
        ),
    ]
